### PR TITLE
Add cave block palette and suvat/scale animators

### PR DESCRIPTION
**Pull request by mudkipdev**
- Added cave block palette
- Improved the look of item lore
- Re-added suvat and scale animators
- Bumped Gradle wrapper
- Bumped Shadow plugin
- Cleaned up code and build script
- Also changed Kafka producer to `@Nullable` because it was throwing a bunch of exceptions locally. Not sure if it's my machine or if the code was simply not tested properly.

## Screenshots

image

### CODE REVIEW

**Comment by LooFifteen** [comment]
This is a lot of unrelated changes in a single pull request.

**Comment by ZakShearman** [comment]
> This is a lot of unrelated changes in a single pull request.

I don't mind it too much here since it's still pretty small and easy to review.

**Comment by ZakShearman** [comment]
Code LGTM - I'll test functionality when I'm home - I wouldn't be surprised if there were issues with the docker image and Pyroscope profiling. If so, will either need to install some packages or revert.

**Review by ZakShearman — CHANGES_REQUESTED** [review]
Code LGTM - I'll test functionality when I'm home - I wouldn't be surprised if there were issues with the docker image and Pyroscope profiling. If so, will either need to install some packages or revert.

**Comment by ZakShearman** [comment]
As suspected the container change breaks Pyroscope. I'd recommend leaving the Dockerfile as is for now or doing it in a separate PR.

It would be best to blanket change this when Java 25 LTS is released (next time we likely upgrade). We're using this specific Azul because we updated to Java 21 too early and it was one of the only ones available (not blaming anyone 😉). lol.

**Comment by ZakShearman** [comment]
Bugs:
- Jump animation -> the blocks look like they jump when they lock into place changing from entities to blocks. The maths is likely a bit off on this.
- Jump animation -> Block entities have collisions so if multiple gen at the same  time, they can collide wither other placed blocks, slide and not land in the right place.

**Comment by ZakShearman** [comment]
If needed we can just move the jump animation to a separate PR for the future. It was previously broken, dead code anyway.

**Comment by ZakShearman** [comment]
If we're happy I will remove the jump animation and leave it as dead code for now so it can be looked at again later. I'll do this later today or tomorrow.

**Review by ZakShearman — APPROVED** [review]

**Pull request merged**
